#ifndef SM_LIMITS_H
#define SM_LIMITS_H

#define DEFAULT_SCAN_INTERVAL_US 15000000u
#define DEFAULT_SCAN_DEPTH 1u
#define DEFAULT_STABILITY_WAIT_SECONDS 10u
#define DEFAULT_AUTO_REMOVE_MISSING_DELAY_SECONDS 300u
#define DEFAULT_KSTUFF_PAUSE_DELAY_IMAGE_SECONDS 25u
#define DEFAULT_KSTUFF_PAUSE_DELAY_DIRECT_SECONDS 15u
#define FAN_TARGET_TEMPERATURE_SYSTEM 0u
#define MIN_FAN_TARGET_TEMPERATURE_C 50u
#define MAX_FAN_TARGET_TEMPERATURE_C 91u
#define MAX_PENDING 512
#define MAX_IMAGE_MOUNTS 2048
#define MAX_IMAGE_TITLES 8192
#define MAX_IMAGE_MODE_RULES 128
#define MAX_KSTUFF_TITLE_RULES 128
#define MAX_FAKELIB_EXCLUDE_RULES 128
#define PATH_STATE_CAPACITY MAX_PENDING
#define TITLE_STATE_CAPACITY MAX_PENDING
#define STATE_HASH_SIZE 1024u
#define MAX_SCAN_PATHS 256

#define MAX_FAILED_MOUNT_ATTEMPTS 2
#define MAX_REGISTER_ATTEMPTS 2
#define MAX_MISSING_PARAM_SCAN_ATTEMPTS 3
#define MAX_IMAGE_MOUNT_ATTEMPTS 3
#define MAX_LAYERED_UNMOUNT_ATTEMPTS 4
#define MAX_IMAGE_CHAIN_DEPTH 8

#define LVD_RELEASE_WAIT_MAX_US 15000000u
#define LVD_RELEASE_WAIT_POLL_US 500000u
#define GAME_LIFECYCLE_POLL_INTERVAL_US 250000u
#define GAME_APPINFO_LOOKUP_TIMEOUT_US 1000000u
// Keep a dead game PID eligible for ExitSpawn/LoadExec replacement while the
// title sandbox still exists. Once the sandbox disappears, retain a short
// grace window so a transient sandbox transition cannot tear down the runtime
// before the replacement NOTE_EXEC is resolved.
#define GAME_PROCESS_HANDOFF_GRACE_US 1000000u
// Keep a slow fallback in case the /mnt/sandbox vnode watch is revoked.
#define GAME_PROCESS_HANDOFF_FALLBACK_POLL_US 5000000u
#define GAME_SLEEP_EXIT_TIMEOUT_US 5000000u
#define RUNTIME_RESUME_GRACE_US 10000000u
#define RUNTIME_RESUME_POLL_US 100000u
#define SHELLCORE_MPROTECT_WAIT_MAX_US 30000000u
#define SHELLCORE_MPROTECT_WAIT_POLL_US 100000u
#define KSTUFF_RESTORE_RETRY_US 1000000u
#define SHELLCORE_FLAG_POLL_INTERVAL_US 100000u
#define SHELLCORE_FLAG_SLEEP_POLL_INTERVAL_US 500000u
#define MIN_SCAN_DEPTH 1u
#define MAX_SCAN_DEPTH 2u
#define MIN_SCAN_INTERVAL_SECONDS 1u
#define MAX_SCAN_INTERVAL_SECONDS 3600u
#define MAX_STABILITY_WAIT_SECONDS 3600u
#define MIN_AUTO_REMOVE_MISSING_DELAY_SECONDS 1u
#define MAX_AUTO_REMOVE_MISSING_DELAY_SECONDS 86400u
#define MAX_KSTUFF_PAUSE_DELAY_SECONDS 3600u

#define APP_DB_QUERY_BUSY_RETRIES 3
#define APP_DB_UPDATE_BUSY_RETRIES 25
#define APP_DB_PREPARE_BUSY_RETRIES 25
#define APP_DB_BUSY_RETRY_SLEEP_US 200000u
#define APP_DB_BUSY_TIMEOUT_MS 5000

#define MAX_PATH 1024
#define MAX_TITLE_ID 32
#define MAX_TITLE_NAME 256
#define MAX_CONTENT_ID 128
#define MAX_APP_DB_TIMESTAMP 64
#define MAX_API_BIND_ADDRESS 16
#define MAX_PARAM_JSON_SIZE (1024u * 1024u)

#endif
