#!/usr/bin/env python3
"""Generate SceShellCore lifecycle offsets from a flat ELF directory.

Input files must be named ``SceShellCoreXXX.elf`` or ``SceShellCoreXXXX.elf``.
The last two digits are the minor firmware version; the preceding digits are
the major version.  For example, ``SceShellCore1140.elf`` is firmware 11.40.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

from generate_shellcore_offsets import ShellCore, TARGET_NAMES, firmware_key


SHELLCORE_NAME = re.compile(r"^SceShellCore(\d{3,4})\.elf$")


def firmware_files(root: Path) -> list[tuple[int, int, Path]]:
    result: list[tuple[int, int, Path]] = []
    for path in root.iterdir():
        if not path.is_file():
            continue
        match = SHELLCORE_NAME.fullmatch(path.name)
        if match is None:
            continue
        version = match.group(1)
        result.append((int(version[:-2]), int(version[-2:]), path))
    return sorted(result, key=lambda item: (item[0], item[1]))


def generate(root: Path) -> str:
    records: list[str] = []
    for major, minor, path in firmware_files(root):
        firmware_name = f"{major}.{minor:02d}"
        shellcore = ShellCore(path)
        targets = shellcore.locate_targets()
        records.append(
            "  {\n"
            f"    .firmware = 0x{firmware_key(firmware_name):04x}u,\n"
            f"    .name = \"{firmware_name}\",\n"
            "    .targets = {"
            + ", ".join(
                "{.offset = "
                f"0x{targets[name]:x}u, .patch_size = "
                f"{shellcore.patch_size(targets[name])}u}}"
                for name in TARGET_NAMES
            )
            + "},\n  }"
        )
    return (
        "/* Generated by tools/generate_shellcore_offsets_from_files.py. */\n"
        + ",\n".join(records)
        + "\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate offsets from SceShellCoreXXXX.elf files"
    )
    parser.add_argument("root", type=Path, help="directory containing the ELF files")
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    output = generate(args.root)
    if args.output:
        with args.output.open("w", encoding="utf-8", newline="\n") as file:
            file.write(output)
    else:
        print(output, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
